name: Fuzz

on:
  [pull_request, workflow_dispatch]

jobs:
  fuzz:
    name: Fuzz  ${{matrix.target}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [fast_float, roundtrip_f64]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rust-src
      - run: cargo install cargo-fuzz
      - run: cargo check
      - run: cd fuzz
      - run: cargo fuzz run --release ${{matrix.target}} -- -max_total_time=150
      - run: cargo fuzz run --release ${{matrix.target}} --sanitizer memory -- -max_total_time=150
