name: Lint

on:
  [push, pull_request, workflow_dispatch]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt, clippy
      - run: cargo check
      - run: cargo fmt -- --check
      - run: RUSTFLAGS="--deny warnings" cargo build
      - run: cargo clippy --all-features -- --deny warnings
